/// <reference path="../pb_data/types.d.ts" />
// Beyfest 2026 tournament schema. One active tournament at a time; the group
// draw and bracket are generated by the SvelteKit server (which imports the
// zero-dependency engine) and written here. Clients only ever read (public
// read on every collection); all writes require an authenticated organiser.
//
// Collections are created in dependency order so relation fields can point at
// the id returned by the preceding app.save(). The down migration reverses it.
migrate(
  (app) => {
    // ─── organisers (auth) — the single shared login ───────────────────────
    const organisers = new Collection({
      type: "auth",
      name: "organisers",
      fields: [{ name: "name", type: "text", required: false }],
    });
    app.save(organisers);

    // ─── tournaments ───────────────────────────────────────────────────────
    const tournaments = new Collection({
      type: "base",
      name: "tournaments",
      fields: [
        { name: "name", type: "text", required: true },
        { name: "playerCount", type: "number", required: true },
        { name: "structureKey", type: "number", required: true },
        {
          name: "status",
          type: "select",
          required: true,
          maxSelect: 1,
          values: ["setup", "group_stage", "knockout", "complete"],
        },
        { name: "createdAt", type: "autodate", onCreate: true, onUpdate: false },
        { name: "updatedAt", type: "autodate", onCreate: true, onUpdate: true },
      ],
    });
    app.save(tournaments);

    // ─── groups ─────────────────────────────────────────────────────────────
    const groups = new Collection({
      type: "base",
      name: "groups",
      fields: [
        { name: "tournament", type: "relation", required: true, collectionId: tournaments.id, maxSelect: 1, cascadeDelete: true },
        { name: "index", type: "number" }, // 0-based (not "required": PB treats 0 as blank)
        { name: "name", type: "text", required: true }, // "Group 1"
        { name: "size", type: "number", required: true },
        { name: "format", type: "select", required: true, maxSelect: 1, values: ["single", "double"] },
        { name: "complete", type: "bool" },
      ],
    });
    app.save(groups);

    // ─── players ─────────────────────────────────────────────────────────────
    const players = new Collection({
      type: "base",
      name: "players",
      fields: [
        { name: "tournament", type: "relation", required: true, collectionId: tournaments.id, maxSelect: 1, cascadeDelete: true },
        { name: "name", type: "text", required: true },
        { name: "group", type: "relation", required: false, collectionId: groups.id, maxSelect: 1 },
        { name: "groupIndex", type: "number" }, // denormalised 0-based group index for the engine
        { name: "drawOrder", type: "number" },
        { name: "finalGroupRank", type: "number" }, // 1-based, null until the group settles
        { name: "eliminated", type: "bool" },
      ],
    });
    app.save(players);

    // ─── matches ─────────────────────────────────────────────────────────────
    const matches = new Collection({
      type: "base",
      name: "matches",
      fields: [
        { name: "tournament", type: "relation", required: true, collectionId: tournaments.id, maxSelect: 1, cascadeDelete: true },
        {
          name: "stage",
          type: "select",
          required: true,
          maxSelect: 1,
          values: ["group", "wb_rr", "lb_rr", "ub", "lb", "wb", "mb", "gf"],
        },
        { name: "code", type: "text", required: true }, // "G1-1", "MB3", "GF1"
        { name: "roundLabel", type: "text", required: true },
        { name: "orderIndex", type: "number", required: true },
        { name: "group", type: "relation", required: false, collectionId: groups.id, maxSelect: 1 },
        { name: "groupIndex", type: "number" },
        { name: "slot1", type: "json", maxSize: 2000000 }, // Slot descriptor, null once resolved
        { name: "slot2", type: "json", maxSize: 2000000 },
        { name: "p1", type: "relation", required: false, collectionId: players.id, maxSelect: 1 },
        { name: "p2", type: "relation", required: false, collectionId: players.id, maxSelect: 1 },
        { name: "p1Score", type: "number" },
        { name: "p2Score", type: "number" },
        { name: "winner", type: "relation", required: false, collectionId: players.id, maxSelect: 1 },
        { name: "loser", type: "relation", required: false, collectionId: players.id, maxSelect: 1 },
        { name: "matchStatus", type: "select", required: true, maxSelect: 1, values: ["pending", "ready", "done"] },
      ],
    });
    app.save(matches);

    // ─── access rules ────────────────────────────────────────────────────────
    // Public read everywhere; writes require an authenticated organiser.
    const authed = '@request.auth.collectionName = "organisers"';
    for (const name of ["tournaments", "groups", "players", "matches"]) {
      const c = app.findCollectionByNameOrId(name);
      c.listRule = "";
      c.viewRule = "";
      c.createRule = authed;
      c.updateRule = authed;
      c.deleteRule = authed;
      app.save(c);
    }
  },
  (app) => {
    for (const name of ["matches", "players", "groups", "tournaments", "organisers"]) {
      try {
        app.delete(app.findCollectionByNameOrId(name));
      } catch (_) {
        /* already gone */
      }
    }
  },
);
